name: atlassian-devbox mvn build
on:
  push:
    paths:
      - 'pom.xml'
      - 'confluence-devbox/**'

jobs:
  mvn-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
          uses: actions/setup-java@v2
          with:
            java-version: '8'
            distribution: 'adopt'
      - name: Build with Maven
          run: mvn --batch-mode verify
